TASK_CONFIG = {
    "task_name": "xlerobot_grasp",
    "camera_names": ["head_cam", "right_arm_cam", "left_arm_cam"],
    "state_dim": 6,
    "action_dim": 6,
    "policy_config": {
        "chunk_size": 40,
        "hidden_dim": 512,
        "dim_feedforward": 3200,
        "nheads": 8,
        "enc_layers": 4,
        "dec_layers": 7,
        "backbone": "resnet18",
        "lr_backbone": 1e-5,
        "kl_weight": 10,
        "temporal_agg": True,
        "max_timesteps": 300,
        "dropout": 0.1,
        "pre_norm": False,
        "masks": False,
        "dilation": False,
        "position_embedding": "sine",
        "weight_decay": 1e-4,
    },
    "num_epochs": 3000,
    "batch_size": 8,
    "lr": 1e-4,
    "validate_every": 100,
    "save_every": 500,
    "data_dir": "teleop/act/data/hdf5",
}

BLUETHINK_CONFIG = {
    "task_name": "bluethink_clear_table",
    "camera_names": ["base_cam", "left_ee_cam", "right_ee_cam"],
    "state_dim": 14,
    "action_dim": 14,
    "policy_config": {
        "chunk_size": 100,
        "hidden_dim": 512,
        "dim_feedforward": 3200,
        "nheads": 8,
        "enc_layers": 4,
        "dec_layers": 1,
        "backbone": "resnet18",
        "lr_backbone": 1e-5,
        "kl_weight": 10,
        "temporal_agg": False,
        "max_timesteps": 300,
        "dropout": 0.1,
        "pre_norm": False,
        "masks": False,
        "dilation": False,
        "position_embedding": "sine",
        "weight_decay": 1e-4,
    },
    "num_epochs": 3000,
    "batch_size": 8,
    "lr": 1e-5,
    "validate_every": 100,
    "save_every": 500,
    "data_dir": "teleop/act/data/bluethink_hdf5",
}
