last_updated: 初始状态
locations:
  nav_000:
    fixture: counter
    objects:
    - plate
    - ketchup
  nav_001:
    fixture: counter
    objects:
    - apple
    - cup
    - bowl
  nav_008:
    fixture: null
    objects: []
  nav_011:
    fixture: null
    objects: []
  nav_014:
    fixture: null
    objects: []
  nav_017:
    fixture: null
    objects: []
  nav_020:
    fixture: null
    objects: []
  nav_022:
    fixture: null
    objects: []
  nav_066:
    fixture: null
    objects: []
  robot_hand:
    fixture: null
    objects: []
